"""
github_open_pr — deterministic CODE skill.

Opens a draft PR, adds the 'security' label, and comments '/e2e' to trigger e2e build.
Safety gate: only operates on kim-codefresh/ repos.
"""
import os
import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

from step_types.github_api import _require_kim_codefresh_repo, github_request


def _ensure_label(repo: str, label: str, color: str = "e11d48"):
    """Create label if it doesn't exist."""
    existing = github_request("GET", f"/repos/{repo}/labels/{label}")
    if not existing:
        github_request("POST", f"/repos/{repo}/labels", {
            "name": label, "color": color, "description": "Security vulnerability fix"
        })


def execute(state: dict, config: dict) -> dict:
    target_repo = state.get("target_repo") or os.getenv("GITHUB_REPO", "")
    repo = _require_kim_codefresh_repo(target_repo)
    branch_name = state.get("branch_name")
    base_branch = config.get("base_branch", "master")
    vulnerabilities = state.get("vulnerabilities", [])
    ticket_id = state.get("ticket_id", "")
    commit_message = state.get("commit_message", "fix: CVE remediation")

    if not branch_name:
        raise ValueError("branch_name missing from state")

    # Build PR title and body
    cve_ids = list({v.get("cve") for v in vulnerabilities if v.get("cve")})
    cve_list = "\n".join(
        f"- [{v['cve']}]({v.get('link', '')}) — `{v['packages']}@{v['packageVersion']}` → `{v.get('fix_version', 'see status')}`"
        for v in vulnerabilities if v.get("cve")
    )
    severity_list = ", ".join({v.get("severity", "").upper() for v in vulnerabilities if v.get("severity")})

    pr_title = f"fix: {ticket_id} — {', '.join(cve_ids)}"
    pr_body = f"""## Security Fix — {ticket_id}

**Severity:** {severity_list}

### CVEs Fixed
{cve_list}

### Changes
Bumped transitive dependencies via `resolutions` in `package.json` to enforce safe versions.

### Verification
- [ ] Local scan clean (twistcli)
- [ ] CI image scan passes (see Security Report below after build)
- [ ] No regressions in e2e

---
> 🤖 Generated by agent-harness · [{ticket_id}](https://linear.app/octopus/issue/{ticket_id})

## Labels
`security` — triggers image scanning in CI build

## PR Comments
`/e2e` — triggers E2E build
"""

    # Ensure security label exists
    _ensure_label(repo, "security")

    # Check if PR already open for this branch
    existing_prs = github_request("GET", f"/repos/{repo}/pulls?head={repo.split('/')[0]}:{branch_name}&state=open")
    if existing_prs:
        pr = existing_prs[0]
        print(f"[github_open_pr] PR already exists: #{pr['number']} {pr['html_url']}")
        return {
            "pr": {
                "number": pr["number"],
                "url": pr["html_url"],
                "title": pr["title"],
                "branch": branch_name,
                "status": "open",
            }
        }

    print(f"[github_open_pr] Opening PR: {pr_title}")
    pr = github_request("POST", f"/repos/{repo}/pulls", {
        "title": pr_title,
        "body": pr_body,
        "head": branch_name,
        "base": base_branch,
        "draft": False,
    })

    pr_number = pr["number"]
    print(f"[github_open_pr] ✅ PR #{pr_number} opened: {pr['html_url']}")

    # Add security label
    github_request("POST", f"/repos/{repo}/issues/{pr_number}/labels", ["security"])
    print(f"[github_open_pr] ✅ Label 'security' added")

    # Comment /e2e to trigger e2e build
    github_request("POST", f"/repos/{repo}/issues/{pr_number}/comments", {"body": "/e2e"})
    print(f"[github_open_pr] ✅ Commented /e2e")

    return {
        "pr": {
            "number": pr_number,
            "url": pr["html_url"],
            "title": pr_title,
            "branch": branch_name,
            "status": "open",
        }
    }
